export type DirectoryAlumni = {
  id: string;
  name: string;
  degree: string;
  department: string;
  batch: number;
  headline: string;
  company: string;
  role: string;
  city: string;
  country: string;
  isVerified: boolean;
  isMentor: boolean;
  isOpenToWork: boolean;
  ctc?: string;
};

export const alumniDirectory: DirectoryAlumni[] = [
  {
    id: "rubal-waliya",
    name: "Rubal Waliya",
    degree: "B.Tech",
    department: "Computer Science",
    batch: 2019,
    headline:
      "Building scalable distributed systems and mentoring the next generation of engineers.",
    company: "Google",
    role: "Software Development Engineer",
    city: "Bangalore",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
    ctc: "64.00 LPA",
  },
  {
    id: "bhupesh-sharma",
    name: "Bhupesh Sharma",
    degree: "MBA",
    department: "Management",
    batch: 2014,
    headline:
      "Leading cross-functional engineering teams to deliver customer-centric products.",
    company: "Infosys",
    role: "Technical Lead",
    city: "Pune",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
    ctc: "24.00 LPA",
  },
  {
    id: "najil-khan",
    name: "Najil Khan",
    degree: "B.Tech",
    department: "Information Technology",
    batch: 2020,
    headline:
      "Full-stack developer focused on clean architecture and delightful user experiences.",
    company: "Flipkart",
    role: "Software Developer",
    city: "Bangalore",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: false,
    ctc: "20.59 LPA",
  },
  {
    id: "kanak-sanpal",
    name: "Kanak Sanpal",
    degree: "B.Tech",
    department: "Computer Science",
    batch: 2020,
    headline:
      "Passionate about building performant web platforms and developer tooling.",
    company: "Razorpay",
    role: "Software Developer",
    city: "Jaipur",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: false,
    ctc: "18.00 LPA",
  },
  {
    id: "ritesh-mishra",
    name: "Ritesh Mishra",
    degree: "M.Tech",
    department: "Computer Science",
    batch: 2018,
    headline:
      "Researcher turned engineer, working on machine learning infrastructure at scale.",
    company: "Microsoft",
    role: "Software Developer",
    city: "Hyderabad",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
    ctc: "17.83 LPA",
  },
  {
    id: "priyanka-sharma",
    name: "Priyanka Sharma",
    degree: "MCA",
    department: "Computer Applications",
    batch: 2019,
    headline:
      "DevOps engineer automating reliable, secure, and observable cloud platforms.",
    company: "Amazon Web Services",
    role: "DevOps Engineer",
    city: "Bangalore",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
    ctc: "17.50 LPA",
  },
  {
    id: "aarav-mehta",
    name: "Aarav Mehta",
    degree: "B.Tech",
    department: "Mechanical",
    batch: 2016,
    headline:
      "Designing efficient automotive systems with a focus on sustainability.",
    company: "Tata Motors",
    role: "Design Engineer",
    city: "Pune",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: true,
  },
  {
    id: "ishita-verma",
    name: "Ishita Verma",
    degree: "MBA",
    department: "Management",
    batch: 2017,
    headline:
      "Marketing leader helping consumer brands tell authentic stories.",
    company: "Hindustan Unilever",
    role: "Brand Manager",
    city: "Mumbai",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
  },
  {
    id: "rohan-gupta",
    name: "Rohan Gupta",
    degree: "B.Tech",
    department: "Electronics",
    batch: 2018,
    headline:
      "Embedded systems engineer building IoT solutions for smart cities.",
    company: "Qualcomm",
    role: "Embedded Engineer",
    city: "Bangalore",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: true,
  },
  {
    id: "sneha-patel",
    name: "Sneha Patel",
    degree: "BCA",
    department: "Computer Applications",
    batch: 2021,
    headline:
      "Frontend developer crafting accessible and delightful web experiences.",
    company: "Zoho",
    role: "UI Developer",
    city: "Chennai",
    country: "India",
    isVerified: false,
    isMentor: false,
    isOpenToWork: true,
  },
  {
    id: "vikram-singh",
    name: "Vikram Singh",
    degree: "B.Tech",
    department: "Civil",
    batch: 2015,
    headline:
      "Infrastructure project manager delivering large-scale public works.",
    company: "Larsen & Toubro",
    role: "Project Manager",
    city: "Delhi",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
  },
  {
    id: "ananya-iyer",
    name: "Ananya Iyer",
    degree: "B.Tech",
    department: "Computer Science",
    batch: 2021,
    headline:
      "Data scientist turning messy data into actionable business insights.",
    company: "Swiggy",
    role: "Data Scientist",
    city: "Bangalore",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: true,
  },
  {
    id: "kabir-joshi",
    name: "Kabir Joshi",
    degree: "M.Tech",
    department: "Mechanical",
    batch: 2014,
    headline:
      "R&D lead for electric vehicle powertrain systems.",
    company: "Mahindra Electric",
    role: "R&D Lead",
    city: "Chennai",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
  },
  {
    id: "meera-nair",
    name: "Meera Nair",
    degree: "MCA",
    department: "Computer Applications",
    batch: 2016,
    headline:
      "Cloud architect designing resilient multi-region systems.",
    company: "Oracle",
    role: "Cloud Architect",
    city: "Hyderabad",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
  },
  {
    id: "arjun-rao",
    name: "Arjun Rao",
    degree: "B.Tech",
    department: "Information Technology",
    batch: 2019,
    headline:
      "Cybersecurity specialist protecting financial systems from evolving threats.",
    company: "PayPal",
    role: "Security Engineer",
    city: "Bangalore",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: true,
  },
  {
    id: "tanvi-desai",
    name: "Tanvi Desai",
    degree: "MBA",
    department: "Management",
    batch: 2018,
    headline:
      "Product manager shipping user-loved features for global audiences.",
    company: "Atlassian",
    role: "Product Manager",
    city: "Sydney",
    country: "Australia",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
  },
  {
    id: "harsh-vardhan",
    name: "Harsh Vardhan",
    degree: "B.Tech",
    department: "Computer Science",
    batch: 2017,
    headline:
      "Backend engineer building high-throughput payment systems.",
    company: "Stripe",
    role: "Backend Engineer",
    city: "Singapore",
    country: "Singapore",
    isVerified: true,
    isMentor: false,
    isOpenToWork: false,
  },
  {
    id: "pooja-reddy",
    name: "Pooja Reddy",
    degree: "B.Tech",
    department: "Electronics",
    batch: 2020,
    headline:
      "VLSI design engineer working on next-generation processors.",
    company: "Intel",
    role: "VLSI Engineer",
    city: "Bangalore",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: true,
  },
  {
    id: "aditya-kulkarni",
    name: "Aditya Kulkarni",
    degree: "M.Tech",
    department: "Computer Science",
    batch: 2015,
    headline:
      "Engineering manager growing high-performing platform teams.",
    company: "Uber",
    role: "Engineering Manager",
    city: "San Francisco",
    country: "USA",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
  },
  {
    id: "nisha-bansal",
    name: "Nisha Bansal",
    degree: "BCA",
    department: "Computer Applications",
    batch: 2022,
    headline:
      "Mobile developer creating smooth cross-platform experiences.",
    company: "PhonePe",
    role: "Mobile Developer",
    city: "Bangalore",
    country: "India",
    isVerified: false,
    isMentor: false,
    isOpenToWork: true,
  },
  {
    id: "siddharth-menon",
    name: "Siddharth Menon",
    degree: "B.Tech",
    department: "Mechanical",
    batch: 2013,
    headline:
      "Operations leader streamlining manufacturing supply chains.",
    company: "Bosch",
    role: "Operations Manager",
    city: "Coimbatore",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
  },
  {
    id: "riya-chopra",
    name: "Riya Chopra",
    degree: "MBA",
    department: "Management",
    batch: 2019,
    headline:
      "HR business partner building inclusive and high-trust workplaces.",
    company: "Accenture",
    role: "HR Business Partner",
    city: "Gurgaon",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: false,
  },
  {
    id: "manish-agarwal",
    name: "Manish Agarwal",
    degree: "B.Tech",
    department: "Civil",
    batch: 2017,
    headline:
      "Structural engineer designing safe and sustainable urban infrastructure.",
    company: "AECOM",
    role: "Structural Engineer",
    city: "Ahmedabad",
    country: "India",
    isVerified: true,
    isMentor: false,
    isOpenToWork: true,
  },
  {
    id: "deepika-singh",
    name: "Deepika Singh",
    degree: "MCA",
    department: "Computer Applications",
    batch: 2014,
    headline:
      "QA architect ensuring quality at scale for mission-critical software.",
    company: "Adobe",
    role: "QA Architect",
    city: "Noida",
    country: "India",
    isVerified: true,
    isMentor: true,
    isOpenToWork: false,
  },
];